<?php

use Illuminate\Database\Seeder;
use App\Country;

class CountriesTableSeeder extends Seeder
{
/**
* Run the database seeds.
*
* @return void
*/
public function run()
{
    Country::get()->each->delete();
    $countries = array(
        array('id' => 1,'code' => 'AF' ,'countryName' => "Afghanistan",'phonecode' => 93),
        array('id' => 2,'code' => 'AL' ,'countryName' => "Albania",'phonecode' => 355),
        array('id' => 3,'code' => 'DZ' ,'countryName' => "Algeria",'phonecode' => 213),
        array('id' => 4,'code' => 'AS' ,'countryName' => "American Samoa",'phonecode' => 1684),
        array('id' => 5,'code' => 'AD' ,'countryName' => "Andorra",'phonecode' => 376),
        array('id' => 6,'code' => 'AO' ,'countryName' => "Angola",'phonecode' => 244),
        array('id' => 7,'code' => 'AI' ,'countryName' => "Anguilla",'phonecode' => 1264),
        array('id' => 8,'code' => 'AQ' ,'countryName' => "Antarctica",'phonecode' => 0),
        array('id' => 9,'code' => 'AG' ,'countryName' => "Antigua And Barbuda",'phonecode' => 1268),
        array('id' => 10,'code' => 'AR','countryName' => "Argentina",'phonecode' => 54),
        array('id' => 11,'code' => 'AM','countryName' => "Armenia",'phonecode' => 374),
        array('id' => 12,'code' => 'AW','countryName' => "Aruba",'phonecode' => 297),
        array('id' => 13,'code' => 'AU','countryName' => "Australia",'phonecode' => 61),
        array('id' => 14,'code' => 'AT','countryName' => "Austria",'phonecode' => 43),
        array('id' => 15,'code' => 'AZ','countryName' => "Azerbaijan",'phonecode' => 994),
        array('id' => 16,'code' => 'BS','countryName' => "Bahamas The",'phonecode' => 1242),
        array('id' => 17,'code' => 'BH','countryName' => "Bahrain",'phonecode' => 973),
        array('id' => 18,'code' => 'BD','countryName' => "Bangladesh",'phonecode' => 880),
        array('id' => 19,'code' => 'BB','countryName' => "Barbados",'phonecode' => 1246),
        array('id' => 20,'code' => 'BY','countryName' => "Belarus",'phonecode' => 375),
        array('id' => 21,'code' => 'BE','countryName' => "Belgium",'phonecode' => 32),
        array('id' => 22,'code' => 'BZ','countryName' => "Belize",'phonecode' => 501),
        array('id' => 23,'code' => 'BJ','countryName' => "Benin",'phonecode' => 229),
        array('id' => 24,'code' => 'BM','countryName' => "Bermuda",'phonecode' => 1441),
        array('id' => 25,'code' => 'BT','countryName' => "Bhutan",'phonecode' => 975),
        array('id' => 26,'code' => 'BO','countryName' => "Bolivia",'phonecode' => 591),
        array('id' => 27,'code' => 'BA','countryName' => "Bosnia and Herzegovina",'phonecode' => 387),
        array('id' => 28,'code' => 'BW','countryName' => "Botswana",'phonecode' => 267),
        array('id' => 29,'code' => 'BV','countryName' => "Bouvet Island",'phonecode' => 0),
        array('id' => 30,'code' => 'BR','countryName' => "Brazil",'phonecode' => 55),
        array('id' => 31,'code' => 'IO','countryName' => "British Indian Ocean Territory",'phonecode' => 246),
        array('id' => 32,'code' => 'BN','countryName' => "Brunei",'phonecode' => 673),
        array('id' => 33,'code' => 'BG','countryName' => "Bulgaria",'phonecode' => 359),
        array('id' => 34,'code' => 'BF','countryName' => "Burkina Faso",'phonecode' => 226),
        array('id' => 35,'code' => 'BI','countryName' => "Burundi",'phonecode' => 257),
        array('id' => 36,'code' => 'KH','countryName' => "Cambodia",'phonecode' => 855),
        array('id' => 37,'code' => 'CM','countryName' => "Cameroon",'phonecode' => 237),
        array('id' => 38,'code' => 'CA','countryName' => "Canada",'phonecode' => 1),
        array('id' => 39,'code' => 'CV','countryName' => "Cape Verde",'phonecode' => 238),
        array('id' => 40,'code' => 'KY','countryName' => "Cayman Islands",'phonecode' => 1345),
        array('id' => 41,'code' => 'CF','countryName' => "Central African Republic",'phonecode' => 236),
        array('id' => 42,'code' => 'TD','countryName' => "Chad",'phonecode' => 235),
        array('id' => 43,'code' => 'CL','countryName' => "Chile",'phonecode' => 56),
        array('id' => 44,'code' => 'CN','countryName' => "China",'phonecode' => 86),
        array('id' => 45,'code' => 'CX','countryName' => "Christmas Island",'phonecode' => 61),
        array('id' => 46,'code' => 'CC','countryName' => "Cocos (Keeling) Islands",'phonecode' => 672),
        array('id' => 47,'code' => 'CO','countryName' => "Colombia",'phonecode' => 57),
        array('id' => 48,'code' => 'KM','countryName' => "Comoros",'phonecode' => 269),
        array('id' => 49,'code' => 'CG','countryName' => "Congo",'phonecode' => 242),
        array('id' => 50,'code' => 'CD','countryName' => "Congo The Democratic Republic Of The",'phonecode' => 242),
        array('id' => 51,'code' => 'CK','countryName' => "Cook Islands",'phonecode' => 682),
        array('id' => 52,'code' => 'CR','countryName' => "Costa Rica",'phonecode' => 506),
        array('id' => 53,'code' => 'CI','countryName' => "Cote D Ivoire (Ivory Coast)",'phonecode' => 225),
        array('id' => 54,'code' => 'HR','countryName' => "Croatia (Hrvatska)",'phonecode' => 385),
        array('id' => 55,'code' => 'CU','countryName' => "Cuba",'phonecode' => 53),
        array('id' => 56,'code' => 'CY','countryName' => "Cyprus",'phonecode' => 357),
        array('id' => 57,'code' => 'CZ','countryName' => "Czech Republic",'phonecode' => 420),
        array('id' => 58,'code' => 'DK','countryName' => "Denmark",'phonecode' => 45),
        array('id' => 59,'code' => 'DJ','countryName' => "Djibouti",'phonecode' => 253),
        array('id' => 60,'code' => 'DM','countryName' => "Dominica",'phonecode' => 1767),
        array('id' => 61,'code' => 'DO','countryName' => "Dominican Republic",'phonecode' => 1809),
        array('id' => 62,'code' => 'TP','countryName' => "East Timor",'phonecode' => 670),
        array('id' => 63,'code' => 'EC','countryName' => "Ecuador",'phonecode' => 593),
        array('id' => 64,'code' => 'EG','countryName' => "Egypt",'phonecode' => 20),
        array('id' => 65,'code' => 'SV','countryName' => "El Salvador",'phonecode' => 503),
        array('id' => 66,'code' => 'GQ','countryName' => "Equatorial Guinea",'phonecode' => 240),
        array('id' => 67,'code' => 'ER','countryName' => "Eritrea",'phonecode' => 291),
        array('id' => 68,'code' => 'EE','countryName' => "Estonia",'phonecode' => 372),
        array('id' => 69,'code' => 'ET','countryName' => "Ethiopia",'phonecode' => 251),
        array('id' => 70,'code' => 'XA','countryName' => "External Territories of Australia",'phonecode' => 61),
        array('id' => 71,'code' => 'FK','countryName' => "Falkland Islands",'phonecode' => 500),
        array('id' => 72,'code' => 'FO','countryName' => "Faroe Islands",'phonecode' => 298),
        array('id' => 73,'code' => 'FJ','countryName' => "Fiji Islands",'phonecode' => 679),
        array('id' => 74,'code' => 'FI','countryName' => "Finland",'phonecode' => 358),
        array('id' => 75,'code' => 'FR','countryName' => "France",'phonecode' => 33),
        array('id' => 76,'code' => 'GF','countryName' => "French Guiana",'phonecode' => 594),
        array('id' => 77,'code' => 'PF','countryName' => "French Polynesia",'phonecode' => 689),
        array('id' => 78,'code' => 'TF','countryName' => "French Southern Territories",'phonecode' => 0),
        array('id' => 79,'code' => 'GA','countryName' => "Gabon",'phonecode' => 241),
        array('id' => 80,'code' => 'GM','countryName' => "Gambia The",'phonecode' => 220),
        array('id' => 81,'code' => 'GE','countryName' => "Georgia",'phonecode' => 995),
        array('id' => 82,'code' => 'DE','countryName' => "Germany",'phonecode' => 49),
        array('id' => 83,'code' => 'GH','countryName' => "Ghana",'phonecode' => 233),
        array('id' => 84,'code' => 'GI','countryName' => "Gibraltar",'phonecode' => 350),
        array('id' => 85,'code' => 'GR','countryName' => "Greece",'phonecode' => 30),
        array('id' => 86,'code' => 'GL','countryName' => "Greenland",'phonecode' => 299),
        array('id' => 87,'code' => 'GD','countryName' => "Grenada",'phonecode' => 1473),
        array('id' => 88,'code' => 'GP','countryName' => "Guadeloupe",'phonecode' => 590),
        array('id' => 89,'code' => 'GU','countryName' => "Guam",'phonecode' => 1671),
        array('id' => 90,'code' => 'GT','countryName' => "Guatemala",'phonecode' => 502),
        array('id' => 91,'code' => 'XU','countryName' => "Guernsey and Alderney",'phonecode' => 44),
        array('id' => 92,'code' => 'GN','countryName' => "Guinea",'phonecode' => 224),
        array('id' => 93,'code' => 'GW','countryName' => "Guinea-Bissau",'phonecode' => 245),
        array('id' => 94,'code' => 'GY','countryName' => "Guyana",'phonecode' => 592),
        array('id' => 95,'code' => 'HT','countryName' => "Haiti",'phonecode' => 509),
        array('id' => 96,'code' => 'HM','countryName' => "Heard and McDonald Islands",'phonecode' => 0),
        array('id' => 97,'code' => 'HN','countryName' => "Honduras",'phonecode' => 504),
        array('id' => 98,'code' => 'HK','countryName' => "Hong Kong S.A.R.",'phonecode' => 852),
        array('id' => 99,'code' => 'HU','countryName' => "Hungary",'phonecode' => 36),
        array('id' => 100,'code' => 'IS','countryName' => "Iceland",'phonecode' => 354),
        array('id' => 101,'code' => 'IN','countryName' => "India",'phonecode' => 91),
        array('id' => 102,'code' => 'ID','countryName' => "Indonesia",'phonecode' => 62),
        array('id' => 103,'code' => 'IR','countryName' => "Iran",'phonecode' => 98),
        array('id' => 104,'code' => 'IQ','countryName' => "Iraq",'phonecode' => 964),
        array('id' => 105,'code' => 'IE','countryName' => "Ireland",'phonecode' => 353),
        array('id' => 106,'code' => 'IL','countryName' => "Israel",'phonecode' => 972),
        array('id' => 107,'code' => 'IT','countryName' => "Italy",'phonecode' => 39),
        array('id' => 108,'code' => 'JM','countryName' => "Jamaica",'phonecode' => 1876),
        array('id' => 109,'code' => 'JP','countryName' => "Japan",'phonecode' => 81),
        array('id' => 110,'code' => 'XJ','countryName' => "Jersey",'phonecode' => 44),
        array('id' => 111,'code' => 'JO','countryName' => "Jordan",'phonecode' => 962),
        array('id' => 112,'code' => 'KZ','countryName' => "Kazakhstan",'phonecode' => 7),
        array('id' => 113,'code' => 'KE','countryName' => "Kenya",'phonecode' => 254),
        array('id' => 114,'code' => 'KI','countryName' => "Kiribati",'phonecode' => 686),
        array('id' => 115,'code' => 'KP','countryName' => "Korea North",'phonecode' => 850),
        array('id' => 116,'code' => 'KR','countryName' => "Korea South",'phonecode' => 82),
        array('id' => 117,'code' => 'KW','countryName' => "Kuwait",'phonecode' => 965),
        array('id' => 118,'code' => 'KG','countryName' => "Kyrgyzstan",'phonecode' => 996),
        array('id' => 119,'code' => 'LA','countryName' => "Laos",'phonecode' => 856),
        array('id' => 120,'code' => 'LV','countryName' => "Latvia",'phonecode' => 371),
        array('id' => 121,'code' => 'LB','countryName' => "Lebanon",'phonecode' => 961),
        array('id' => 122,'code' => 'LS','countryName' => "Lesotho",'phonecode' => 266),
        array('id' => 123,'code' => 'LR','countryName' => "Liberia",'phonecode' => 231),
        array('id' => 124,'code' => 'LY','countryName' => "Libya",'phonecode' => 218),
        array('id' => 125,'code' => 'LI','countryName' => "Liechtenstein",'phonecode' => 423),
        array('id' => 126,'code' => 'LT','countryName' => "Lithuania",'phonecode' => 370),
        array('id' => 127,'code' => 'LU','countryName' => "Luxembourg",'phonecode' => 352),
        array('id' => 128,'code' => 'MO','countryName' => "Macau S.A.R.",'phonecode' => 853),
        array('id' => 129,'code' => 'MK','countryName' => "Macedonia",'phonecode' => 389),
        array('id' => 130,'code' => 'MG','countryName' => "Madagascar",'phonecode' => 261),
        array('id' => 131,'code' => 'MW','countryName' => "Malawi",'phonecode' => 265),
        array('id' => 132,'code' => 'MY','countryName' => "Malaysia",'phonecode' => 60),
        array('id' => 133,'code' => 'MV','countryName' => "Maldives",'phonecode' => 960),
        array('id' => 134,'code' => 'ML','countryName' => "Mali",'phonecode' => 223),
        array('id' => 135,'code' => 'MT','countryName' => "Malta",'phonecode' => 356),
        array('id' => 136,'code' => 'XM','countryName' => "Man (Isle of)",'phonecode' => 44),
        array('id' => 137,'code' => 'MH','countryName' => "Marshall Islands",'phonecode' => 692),
        array('id' => 138,'code' => 'MQ','countryName' => "Martinique",'phonecode' => 596),
        array('id' => 139,'code' => 'MR','countryName' => "Mauritania",'phonecode' => 222),
        array('id' => 140,'code' => 'MU','countryName' => "Mauritius",'phonecode' => 230),
        array('id' => 141,'code' => 'YT','countryName' => "Mayotte",'phonecode' => 269),
        array('id' => 142,'code' => 'MX','countryName' => "Mexico",'phonecode' => 52),
        array('id' => 143,'code' => 'FM','countryName' => "Micronesia",'phonecode' => 691),
        array('id' => 144,'code' => 'MD','countryName' => "Moldova",'phonecode' => 373),
        array('id' => 145,'code' => 'MC','countryName' => "Monaco",'phonecode' => 377),
        array('id' => 146,'code' => 'MN','countryName' => "Mongolia",'phonecode' => 976),
        array('id' => 147,'code' => 'MS','countryName' => "Montserrat",'phonecode' => 1664),
        array('id' => 148,'code' => 'MA','countryName' => "Morocco",'phonecode' => 212),
        array('id' => 149,'code' => 'MZ','countryName' => "Mozambique",'phonecode' => 258),
        array('id' => 150,'code' => 'MM','countryName' => "Myanmar",'phonecode' => 95),
        array('id' => 151,'code' => 'NA','countryName' => "Namibia",'phonecode' => 264),
        array('id' => 152,'code' => 'NR','countryName' => "Nauru",'phonecode' => 674),
        array('id' => 153,'code' => 'NP','countryName' => "Nepal",'phonecode' => 977),
        array('id' => 154,'code' => 'AN','countryName' => "Netherlands Antilles",'phonecode' => 599),
        array('id' => 155,'code' => 'NL','countryName' => "Netherlands The",'phonecode' => 31),
        array('id' => 156,'code' => 'NC','countryName' => "New Caledonia",'phonecode' => 687),
        array('id' => 157,'code' => 'NZ','countryName' => "New Zealand",'phonecode' => 64),
        array('id' => 158,'code' => 'NI','countryName' => "Nicaragua",'phonecode' => 505),
        array('id' => 159,'code' => 'NE','countryName' => "Niger",'phonecode' => 227),
        array('id' => 160,'code' => 'NG','countryName' => "Nigeria",'phonecode' => 234),
        array('id' => 161,'code' => 'NU','countryName' => "Niue",'phonecode' => 683),
        array('id' => 162,'code' => 'NF','countryName' => "Norfolk Island",'phonecode' => 672),
        array('id' => 163,'code' => 'MP','countryName' => "Northern Mariana Islands",'phonecode' => 1670),
        array('id' => 164,'code' => 'NO','countryName' => "Norway",'phonecode' => 47),
        array('id' => 165,'code' => 'OM','countryName' => "Oman",'phonecode' => 968),
        array('id' => 166,'code' => 'PK','countryName' => "Pakistan",'phonecode' => 92),
        array('id' => 167,'code' => 'PW','countryName' => "Palau",'phonecode' => 680),
        array('id' => 168,'code' => 'PS','countryName' => "Palestinian Territory Occupied",'phonecode' => 970),
        array('id' => 169,'code' => 'PA','countryName' => "Panama",'phonecode' => 507),
        array('id' => 170,'code' => 'PG','countryName' => "Papua new Guinea",'phonecode' => 675),
        array('id' => 171,'code' => 'PY','countryName' => "Paraguay",'phonecode' => 595),
        array('id' => 172,'code' => 'PE','countryName' => "Peru",'phonecode' => 51),
        array('id' => 173,'code' => 'PH','countryName' => "Philippines",'phonecode' => 63),
        array('id' => 174,'code' => 'PN','countryName' => "Pitcairn Island",'phonecode' => 0),
        array('id' => 175,'code' => 'PL','countryName' => "Poland",'phonecode' => 48),
        array('id' => 176,'code' => 'PT','countryName' => "Portugal",'phonecode' => 351),
        array('id' => 177,'code' => 'PR','countryName' => "Puerto Rico",'phonecode' => 1787),
        array('id' => 178,'code' => 'QA','countryName' => "Qatar",'phonecode' => 974),
        array('id' => 179,'code' => 'RE','countryName' => "Reunion",'phonecode' => 262),
        array('id' => 180,'code' => 'RO','countryName' => "Romania",'phonecode' => 40),
        array('id' => 181,'code' => 'RU','countryName' => "Russia",'phonecode' => 70),
        array('id' => 182,'code' => 'RW','countryName' => "Rwanda",'phonecode' => 250),
        array('id' => 183,'code' => 'SH','countryName' => "Saint Helena",'phonecode' => 290),
        array('id' => 184,'code' => 'KN','countryName' => "Saint Kitts And Nevis",'phonecode' => 1869),
        array('id' => 185,'code' => 'LC','countryName' => "Saint Lucia",'phonecode' => 1758),
        array('id' => 186,'code' => 'PM','countryName' => "Saint Pierre and Miquelon",'phonecode' => 508),
        array('id' => 187,'code' => 'VC','countryName' => "Saint Vincent And The Grenadines",'phonecode' => 1784),
        array('id' => 188,'code' => 'WS','countryName' => "Samoa",'phonecode' => 684),
        array('id' => 189,'code' => 'SM','countryName' => "San Marino",'phonecode' => 378),
        array('id' => 190,'code' => 'ST','countryName' => "Sao Tome and Principe",'phonecode' => 239),
        array('id' => 191,'code' => 'SA','countryName' => "Saudi Arabia",'phonecode' => 966),
        array('id' => 192,'code' => 'SN','countryName' => "Senegal",'phonecode' => 221),
        array('id' => 193,'code' => 'RS','countryName' => "Serbia",'phonecode' => 381),
        array('id' => 194,'code' => 'SC','countryName' => "Seychelles",'phonecode' => 248),
        array('id' => 195,'code' => 'SL','countryName' => "Sierra Leone",'phonecode' => 232),
        array('id' => 196,'code' => 'SG','countryName' => "Singapore",'phonecode' => 65),
        array('id' => 197,'code' => 'SK','countryName' => "Slovakia",'phonecode' => 421),
        array('id' => 198,'code' => 'SI','countryName' => "Slovenia",'phonecode' => 386),
        array('id' => 199,'code' => 'XG','countryName' => "Smaller Territories of the UK",'phonecode' => 44),
        array('id' => 200,'code' => 'SB','countryName' => "Solomon Islands",'phonecode' => 677),
        array('id' => 201,'code' => 'SO','countryName' => "Somalia",'phonecode' => 252),
        array('id' => 202,'code' => 'ZA','countryName' => "South Africa",'phonecode' => 27),
        array('id' => 203,'code' => 'GS','countryName' => "South Georgia",'phonecode' => 0),
        array('id' => 204,'code' => 'SS','countryName' => "South Sudan",'phonecode' => 211),
        array('id' => 205,'code' => 'ES','countryName' => "Spain",'phonecode' => 34),
        array('id' => 206,'code' => 'LK','countryName' => "Sri Lanka",'phonecode' => 94),
        array('id' => 207,'code' => 'SD','countryName' => "Sudan",'phonecode' => 249),
        array('id' => 208,'code' => 'SR','countryName' => "SuricountryName",'phonecode' => 597),
        array('id' => 209,'code' => 'SJ','countryName' => "Svalbard And Jan Mayen Islands",'phonecode' => 47),
        array('id' => 210,'code' => 'SZ','countryName' => "Swaziland",'phonecode' => 268),
        array('id' => 211,'code' => 'SE','countryName' => "Sweden",'phonecode' => 46),
        array('id' => 212,'code' => 'CH','countryName' => "Switzerland",'phonecode' => 41),
        array('id' => 213,'code' => 'SY','countryName' => "Syria",'phonecode' => 963),
        array('id' => 214,'code' => 'TW','countryName' => "Taiwan",'phonecode' => 886),
        array('id' => 215,'code' => 'TJ','countryName' => "Tajikistan",'phonecode' => 992),
        array('id' => 216,'code' => 'TZ','countryName' => "Tanzania",'phonecode' => 255),
        array('id' => 217,'code' => 'TH','countryName' => "Thailand",'phonecode' => 66),
        array('id' => 218,'code' => 'TG','countryName' => "Togo",'phonecode' => 228),
        array('id' => 219,'code' => 'TK','countryName' => "Tokelau",'phonecode' => 690),
        array('id' => 220,'code' => 'TO','countryName' => "Tonga",'phonecode' => 676),
        array('id' => 221,'code' => 'TT','countryName' => "Trinidad And Tobago",'phonecode' => 1868),
        array('id' => 222,'code' => 'TN','countryName' => "Tunisia",'phonecode' => 216),
        array('id' => 223,'code' => 'TR','countryName' => "Turkey",'phonecode' => 90),
        array('id' => 224,'code' => 'TM','countryName' => "Turkmenistan",'phonecode' => 7370),
        array('id' => 225,'code' => 'TC','countryName' => "Turks And Caicos Islands",'phonecode' => 1649),
        array('id' => 226,'code' => 'TV','countryName' => "Tuvalu",'phonecode' => 688),
        array('id' => 227,'code' => 'UG','countryName' => "Uganda",'phonecode' => 256),
        array('id' => 228,'code' => 'UA','countryName' => "Ukraine",'phonecode' => 380),
        array('id' => 229,'code' => 'AE','countryName' => "United Arab Emirates",'phonecode' => 971),
        array('id' => 230,'code' => 'GB','countryName' => "United Kingdom",'phonecode' => 44),
        array('id' => 231,'code' => 'US','countryName' => "United States",'phonecode' => 1),
        array('id' => 232,'code' => 'UM','countryName' => "United States Minor Outlying Islands",'phonecode' => 1),
        array('id' => 233,'code' => 'UY','countryName' => "Uruguay",'phonecode' => 598),
        array('id' => 234,'code' => 'UZ','countryName' => "Uzbekistan",'phonecode' => 998),
        array('id' => 235,'code' => 'VU','countryName' => "Vanuatu",'phonecode' => 678),
        array('id' => 236,'code' => 'VA','countryName' => "Vatican City State (Holy See)",'phonecode' => 39),
        array('id' => 237,'code' => 'VE','countryName' => "Venezuela",'phonecode' => 58),
        array('id' => 238,'code' => 'VN','countryName' => "Vietnam",'phonecode' => 84),
        array('id' => 239,'code' => 'VG','countryName' => "Virgin Islands (British)",'phonecode' => 1284),
        array('id' => 240,'code' => 'VI','countryName' => "Virgin Islands (US)",'phonecode' => 1340),
        array('id' => 241,'code' => 'WF','countryName' => "Wallis And Futuna Islands",'phonecode' => 681),
        array('id' => 242,'code' => 'EH','countryName' => "Western Sahara",'phonecode' => 212),
        array('id' => 243,'code' => 'YE','countryName' => "Yemen",'phonecode' => 967),
        array('id' => 244,'code' => 'YU','countryName' => "Yugoslavia",'phonecode' => 38),
        array('id' => 245,'code' => 'ZM','countryName' => "Zambia",'phonecode' => 260),
        array('id' => 246,'code' => 'ZW','countryName' => "Zimbabwe",'phonecode' => 263),
        );
        Country::insert($countries);
    }
}